application: urlreveal
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: app.py

- url: /about
  script: app.py

- url: /reveal
  script: app.py

- url: /style
  static_dir: style
